# This file was generated by GoReleaser. DO NOT EDIT.
cask "prrompt" do
  name "prrompt"
  desc "Lightweight git post-commit hook that extracts prompts from commits"
  homepage "https://github.com/Ilnicki010/prrompt"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "prrompt"

  on_macos do
    on_intel do
      url "https://github.com/Ilnicki010/prrompt/releases/download/v#{version}/prrompt_Darwin_x86_64.tar.gz"
      sha256 "b79166180e1a72803789a8b59ac8b557ea6b4e7d56cf3697f034c72eee64c8ac"
    end
    on_arm do
      url "https://github.com/Ilnicki010/prrompt/releases/download/v#{version}/prrompt_Darwin_arm64.tar.gz"
      sha256 "5c1f2aacf13b933dffb87e33bb93bb175a346c3c90d0521a1f775779fd48b57a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Ilnicki010/prrompt/releases/download/v#{version}/prrompt_Linux_x86_64.tar.gz"
      sha256 "ea26ec66d794cc88c4abb22dfe32a53931f9329ae516e6f5fe08069b5acb86ec"
    end
    on_arm do
      url "https://github.com/Ilnicki010/prrompt/releases/download/v#{version}/prrompt_Linux_arm64.tar.gz"
      sha256 "0aa295bd47733c9fde20412b020fd21aa78076ad0f7f164fe1ef5af3e79cf84e"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/prrompt"]
    end
  end

  # No zap stanza required
end
